# The "App Staging" workflow is manually triggered to deploy the application to the staging environment. It builds the
# staging version of the application and deploys it for testing before releasing to production.

name: App Staging

on:
  workflow_dispatch: {}

concurrency:
  group: staging-deployment
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/shared-build.yml
    secrets: inherit
    with:
      env: "staging"

  deploy:
    uses: ./.github/workflows/shared-deploy.yml
    needs: build
    secrets: inherit
    with:
      domain: "stg.app.aragon.org"
      env: "staging"
