name: App Rollback

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to rollback to (e.g., v1.16.0)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/shared-build.yml
    secrets: inherit
    with:
      env: 'production'
      ref: ${{ inputs.tag }}

  deploy:
    needs: build
    uses: ./.github/workflows/shared-deploy.yml
    secrets: inherit
    with:
      domain: 'app.aragon.org'
      env: 'production'
