# The "App Release" workflow is manually triggered to release the application to production. It updates the version and
# changelog, creates a new tag, commits the changes, and pushes them to the repository when triggered on the main branch.

name: App Release

on:
  workflow_dispatch:

concurrency:
  group: app-release
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download infra credentials
        uses: aragon/github-templates/steps/credential-retrieval@v0.2
        with:
          op-token: "${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}"
          op-vault: "kv_app-next_infra"

      - name: Setup
        uses: aragon/app-next/.github/actions/setup@main
        with:
          token: ${{ env.ARABOT_PAT }}
          node-version: 22
      - name: Setup Git config
        run: |
          git config --global user.name "Arabot-1"
          git config --global user.email "arabot-1@users.noreply.github.com"
      - name: Update version and changelog
        # Run prettier on CHANGELOG.md file (used for Github release notes) to remove automatic formatting applied by
        # changeset as Github does not support soft line breaks.
        # (See https://github.com/changesets/changesets/issues/1452, https://github.com/orgs/community/discussions/10981)
        run: |
          yarn changeset version
          yarn prettier --write CHANGELOG.md --print-width 9999999 --ignore-path
        env:
          GITHUB_TOKEN: ${{ env.ARABOT_PAT }}
      - name: Create tag
        run: yarn changeset tag
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Commit changes
        run: |
          git add --all
          git commit -am "Release v${{ steps.package-version.outputs.current-version}}"
          git push --follow-tags
      - name: Read changelog updates
        id: read-changelog
        uses: actions/github-script@v7.0.1
        env:
          version: "${{ steps.package-version.outputs.current-version }}"
          path: ./CHANGELOG.md
        with:
          script: |
            const readChangelog = require('./.github/workflows/scripts/readChangelog.js');
            readChangelog({ github, context, core });
      - name: Create release
        uses: softprops/action-gh-release@v2.2.2
        with:
          prerelease: false
          tag_name: "v${{ steps.package-version.outputs.current-version}}"
          body: ${{ steps.read-changelog.outputs.changes }}
          token: ${{ env.ARABOT_PAT }}
