# The "Shared Build" workflow builds the application for the specified environment by restoring cache, running the
# build, and storing the Next.js build artifacts under the "nextjs-build" name. It is triggered by a `workflow_call`
# and uses the environment variable specified in the input to configure the build.

name: App Shared Build

on:
  workflow_call:
    inputs:
      env:
        description: "Used to setup the correct environment variables for the build"
        required: true
        type: string
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 1
          sparse-checkout: |
            .github/actions/setup
      - name: Setup
        uses: ./.github/actions/setup
      - name: Restore NextJs cache
        uses: actions/cache@v5.0.1
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Build ${{ inputs.env }} application
        run: |
          pnpm run setup ${{ inputs.env }}
          pnpm run build
        env:
          NEXT_PUBLIC_SENTRY_ORG: ${{ vars.NEXT_PUBLIC_SENTRY_ORG }}
          NEXT_PUBLIC_SENTRY_PROJECT: ${{ vars.NEXT_PUBLIC_SENTRY_PROJECT }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          NEXT_SECRET_SENTRY_AUTH_TOKEN: ${{ secrets.NEXT_SECRET_SENTRY_AUTH_TOKEN }}
      - name: Store NextJs build
        uses: actions/upload-artifact@v6.0.0
        with:
          name: nextjs-build
          include-hidden-files: true
          path: |
            ${{ github.workspace }}/.next/
            ${{ github.workspace }}/.env.local
            ${{ github.workspace }}/next-env.d.ts
